name = "rccg-kingdom-parish-app"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "rccg-parish-db"
database_id = "dcc63f58-6079-44ba-900c-ff58bc81c4e8"
